/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.awt.Color;
import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.ImageIcon;

/**
 *
 * @author IFPR
 */
public class JanelaCreditos extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCreditos
     */
    public JanelaCreditos() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        masculinahLB.setVisible(false);
    }
    
    MediaPlayer masculinah;
    
    private void changeMusic(){
        JFXPanel fxPanel = new JFXPanel();
        Media pick = new Media(new File("src/sons/esterEgg.mp3").toURI().toString());   
        masculinah = new MediaPlayer(pick);
        masculinah.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okBT = new javax.swing.JButton();
        masculinahBT = new javax.swing.JButton();
        masculinahLB = new javax.swing.JLabel();
        backgroundLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        okBT.setBackground(new java.awt.Color(204, 204, 255));
        okBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btOk.png"))); // NOI18N
        okBT.setBorderPainted(false);
        okBT.setContentAreaFilled(false);
        okBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okBTMouseExited(evt);
            }
        });
        okBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTActionPerformed(evt);
            }
        });
        jPanel1.add(okBT);
        okBT.setBounds(440, 300, 96, 70);

        masculinahBT.setBorderPainted(false);
        masculinahBT.setContentAreaFilled(false);
        masculinahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinahBTActionPerformed(evt);
            }
        });
        jPanel1.add(masculinahBT);
        masculinahBT.setBounds(170, 280, 20, 20);

        masculinahLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/masculinah.png"))); // NOI18N
        jPanel1.add(masculinahLB);
        masculinahLB.setBounds(43, 40, 300, 400);

        backgroundLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bkgCreditos.png"))); // NOI18N
        jPanel1.add(backgroundLB);
        backgroundLB.setBounds(0, 0, 640, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(640, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void okBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBTMouseEntered
        okBT.setIcon(new ImageIcon("src/imagens/btOkShadow.png"));
    }//GEN-LAST:event_okBTMouseEntered

    private void okBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBTMouseExited
        okBT.setIcon(new ImageIcon("src/imagens/btOk.png"));
    }//GEN-LAST:event_okBTMouseExited

    private void okBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTActionPerformed
        dispose();
    }//GEN-LAST:event_okBTActionPerformed

    private void masculinahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinahBTActionPerformed
        masculinahLB.setVisible(true);
        changeMusic();
    }//GEN-LAST:event_masculinahBTActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton masculinahBT;
    private javax.swing.JLabel masculinahLB;
    private javax.swing.JButton okBT;
    // End of variables declaration//GEN-END:variables
}
