/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import jPuzzle.JPuzzle3x3;
import jPuzzle.JPuzzle4x4;
import jPuzzle.JPuzzle5x5;
import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.ImageIcon;

/**
 *
 * @author IFPR
 */
public class JanelaEscolha extends javax.swing.JFrame {

    /**
     * Creates new form JanelaEscolha
     */
    public JanelaEscolha() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Sliding Puzzle");
        changeMusic(1);
    }
    
    int i = 0;
    MediaPlayer player;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltarBT = new javax.swing.JButton();
        playBT = new javax.swing.JButton();
        op3BT = new javax.swing.JButton();
        op5BT = new javax.swing.JButton();
        op4BT = new javax.swing.JButton();
        backgroundLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 245, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        voltarBT.setBackground(new java.awt.Color(204, 204, 255));
        voltarBT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        voltarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btVoltar.png"))); // NOI18N
        voltarBT.setBorderPainted(false);
        voltarBT.setContentAreaFilled(false);
        voltarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarBTMouseExited(evt);
            }
        });
        voltarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBTActionPerformed(evt);
            }
        });
        jPanel1.add(voltarBT);
        voltarBT.setBounds(20, 30, 80, 60);

        playBT.setBackground(new java.awt.Color(204, 204, 255));
        playBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btOk.png"))); // NOI18N
        playBT.setBorderPainted(false);
        playBT.setContentAreaFilled(false);
        playBT.setEnabled(false);
        playBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playBTMouseExited(evt);
            }
        });
        playBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBTActionPerformed(evt);
            }
        });
        jPanel1.add(playBT);
        playBT.setBounds(336, 478, 150, 70);

        op3BT.setBackground(new java.awt.Color(204, 204, 255));
        op3BT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op3BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btOp3.png"))); // NOI18N
        op3BT.setBorderPainted(false);
        op3BT.setContentAreaFilled(false);
        op3BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                op3BTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                op3BTMouseExited(evt);
            }
        });
        op3BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3BTActionPerformed(evt);
            }
        });
        jPanel1.add(op3BT);
        op3BT.setBounds(70, 200, 200, 200);

        op5BT.setBackground(new java.awt.Color(204, 204, 255));
        op5BT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op5BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btOp5.png"))); // NOI18N
        op5BT.setBorderPainted(false);
        op5BT.setContentAreaFilled(false);
        op5BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op5BTActionPerformed(evt);
            }
        });
        jPanel1.add(op5BT);
        op5BT.setBounds(540, 200, 200, 200);

        op4BT.setBackground(new java.awt.Color(204, 204, 255));
        op4BT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op4BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btOp4.png"))); // NOI18N
        op4BT.setBorderPainted(false);
        op4BT.setContentAreaFilled(false);
        op4BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4BTActionPerformed(evt);
            }
        });
        jPanel1.add(op4BT);
        op4BT.setBounds(300, 200, 200, 200);

        backgroundLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bkgComGato.png"))); // NOI18N
        backgroundLB.setText("jLabel1");
        jPanel1.add(backgroundLB);
        backgroundLB.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeMusic(int i){
        if(i == 0){
            JFXPanel fxPanel = new JFXPanel();
            Media pick = new Media(new File("src/sons/buttonMenu.mp3").toURI().toString());   
            player = new MediaPlayer(pick);
            player.play();
        }
        if(i == 1){
            JFXPanel fxPanel = new JFXPanel();
            Media pick = new Media(new File("src/sons/meow3.mp3").toURI().toString());   
            player = new MediaPlayer(pick);
            player.play();
        }
        
    }
    
    private void voltarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBTActionPerformed
        JanelaPrincipal.isPlaying = true;
        new JanelaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarBTActionPerformed

    private void playBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBTActionPerformed
        if(i == 3)
            new JPuzzle3x3().setVisible(true);
        if(i == 4)
            new JPuzzle4x4().setVisible(true);
        if(i == 5)
            new JPuzzle5x5().setVisible(true);
        dispose();
    }//GEN-LAST:event_playBTActionPerformed

    private void op3BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3BTActionPerformed
        changeMusic(0);
        i = 3;
        playBT.setEnabled(true);
        
        op3BT.setIcon(new ImageIcon("src/imagens/btOp3Shadow.png"));
        op4BT.setIcon(new ImageIcon("src/imagens/btOp4.png"));
        op5BT.setIcon(new ImageIcon("src/imagens/btOp5.png"));
    }//GEN-LAST:event_op3BTActionPerformed

    private void op5BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op5BTActionPerformed
        changeMusic(0);
        i = 5;
        playBT.setEnabled(true);
        
        op5BT.setIcon(new ImageIcon("src/imagens/btOp5Shadow.png"));
        op3BT.setIcon(new ImageIcon("src/imagens/btOp3.png"));
        op4BT.setIcon(new ImageIcon("src/imagens/btOp4.png"));
    }//GEN-LAST:event_op5BTActionPerformed

    private void op4BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4BTActionPerformed
        changeMusic(0);
        i = 4;
        playBT.setEnabled(true);
        
        op4BT.setIcon(new ImageIcon("src/imagens/btOp4Shadow.png"));
        op3BT.setIcon(new ImageIcon("src/imagens/btOp3.png"));
        op5BT.setIcon(new ImageIcon("src/imagens/btOp5.png"));
    }//GEN-LAST:event_op4BTActionPerformed

    private void voltarBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBTMouseEntered
        changeMusic(0);
        voltarBT.setIcon(new ImageIcon("src/imagens/btVoltarShadow.png"));
    }//GEN-LAST:event_voltarBTMouseEntered

    private void voltarBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBTMouseExited
        voltarBT.setIcon(new ImageIcon("src/imagens/btVoltar.png"));
    }//GEN-LAST:event_voltarBTMouseExited

    private void playBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBTMouseEntered
        changeMusic(0);
        playBT.setIcon(new ImageIcon("src/imagens/btOkShadow.png"));
    }//GEN-LAST:event_playBTMouseEntered

    private void playBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBTMouseExited
        playBT.setIcon(new ImageIcon("src/imagens/btOk.png"));
    }//GEN-LAST:event_playBTMouseExited

    private void op3BTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op3BTMouseEntered

    }//GEN-LAST:event_op3BTMouseEntered

    private void op3BTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op3BTMouseExited

    }//GEN-LAST:event_op3BTMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton op3BT;
    private javax.swing.JButton op4BT;
    private javax.swing.JButton op5BT;
    private javax.swing.JButton playBT;
    private javax.swing.JButton voltarBT;
    // End of variables declaration//GEN-END:variables
}
